### ISSUE TITLE
[Feedback] Linux usage

### ISSUE THREAD

**Issue by MostHated** [r4hulCorleone/unity-magic-layout#5]
Hey there,
    I just wanted to let you know, I really like the purpose of this package, getting rid of the minimum size constraint can be super helpful. Unfortunately for us Linux users, though, it is pretty difficult for this package to actually be useful, not because of the package itself, but because of just how shit the experience is in trying to resize panes in the Linux editor. Simply trying to drag a pane, it jumps all over the place and sometimes causes other windows to resize and all this mess. 

The worst part is, it's not always super consistent. You might drag a pane once, and it will be a bit choppy, sure, but other times you go to drag it, and it can jump back and forth several inches as seen below at the later part of the clip, when I go back to the project pane a second time. This is how it currently, and has been for years:

![](https://i.imgur.com/7wgZ8P3.gif)

Just wanted to make sure you were aware, in case anyone comes to you thinking it is your package or something, lol. Nope, that's just Linux.

Thanks,
-MH

**Comment by r4hulCorleone** [comment]
Thanks for your feedback @MostHated, I am sorry to hear that, I am not a linux user so i wasn't aware about this issue with linux users. It is really bad such simple things can get messy, For now I will update the docs to inform others of this issue, For the future, I will check this issue on a linux machine later, who knows, maybe we can find a solution for the issue. Can you specify your OS details & Unity Version?

**Comment by MostHated** [comment]
Sure thing, I am on a Ubuntu based distro called Pop_OS v21.04. That clip was taken in Unity 2020.3, but it happens in all versions for me, up to 2021.2.0b7.

**Comment by r4hulCorleone** [comment]
Thanks for the update, I was surfing the web around the issue and I found [this](https://www.reddit.com/r/Unity3D/comments/6kry4j/performance_problems_on_linux/), if you have some time please give it a try, if you are using Nvidia graphic card: 
- Open Nvidia x server settings > Click open Gl settings > Toggle "Sync to VBlank" to unchecked. > Restart unity.

**Comment by MostHated** [comment]
I appreciate the tip, unfortunately, that was already off. Unless perhaps there happens to exist a perfect combination of different settings, I have tried every setting I could find throughout the last few years. Everything else is perfect and works wonderfully, it is just resizing those windows. Resizing nested split panes typically works fine. You see here, adjusting the Console Pro split pane works normally, the project window split works ok, its choppy, but doesn't jump. But resizing the size between the two actual panes is out of control, lol.

![](https://i.imgur.com/Qxrfhle.gif)

**Comment by MostHated** [comment]
So, this is interesting. I found a setting related to "flipping", which I disabled. The windows still do the random jumping around, but they do it much more smoothly, lol.

![https://i.imgur.com/Rfsjeh2.gif](https://i.imgur.com/Rfsjeh2.gif)
Edit -- it looks like the gif was a bit too large. https://i.imgur.com/Rfsjeh2.gifv

For some reason, one single time I went to move the pane and it worked as it should, but then I did it again, and bounce city. I don't quite understand what is going on.

**Comment by r4hulCorleone** [comment]
Sorry for late response, I was sick during last weeks, I tested this issue on a Pop os machine, and i had same result in Unity 2020.3, i tried some changes like:
- Forcing unity to update opened windows( It refreshes all windows, so after resizing you get clean view, but no help with effects during resizing)
- Playing with Linux compositors like [compton](https://github.com/chjj/compton) didn't help.

**Comment by MostHated** [comment]
No worries, hope you are feeling better. Yeah, though, unfortunately, it just seems like it is something I am just going to have to continue to deal with until whenever. Strangely, though, Unity is the only app in which I have ever experienced this, I guess just something about how the docked panes resize, as moving nested panes has never really been an issue. I was considering trying to see if I could manually set the sizes or something along those lines, just to have less of a headache, as every time I open Unity I have to fix them in some manner.

**Comment by r4hulCorleone** [comment]
I suggest [reporting the bug/issue](https://unity3d.com/unity/qa/bug-reporting) using their bug reporter. Share the issue link so I can vote for it, hope they fix it in future releases.
